version: '3.1'

networks:
  app-tier:
    driver: bridge

services:
  mysql-db:
    image: mysql:8.0
    networks:
      - app-tier
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./db-config/init-db.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_manager
      MYSQL_USER: user_manager
      MYSQL_PASSWORD: user_manager

  adminer:
    image: adminer
    networks:
      - app-tier
    restart: always
    ports:
      - 9000:8080

  app:
    image: ricardo/usermanager
    networks:
      - app-tier
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: mysql-db:3306