# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./db-config/init-db.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_manager
      MYSQL_USER: user_manager
      MYSQL_PASSWORD: user_manager

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080